apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 2 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: us-east1-docker.pkg.dev/roigcp-240403-user405/sample-firestore/internal
        env: 
        - name: PORT
          value: "8082"
        - name: GOOGLE_CLOUD_PROJECT
          value: "roigcp-240403-user405"
        ports:
        - containerPort: 8082
            
        
